---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
    driver:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["private_network", {ip: "192.168.33.1"}]

suites:
  - name: default
    run_list:
      - recipe[wordpress_cookbook::default]
    attributes:
